[package]
name = "c9watch"
version = "0.2.1"
description = "Monitor and control all your Claude Code sessions from one place"
authors = ["minchenlee"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "c9watch_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-notification = "2"
tauri-plugin-opener = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = "0.32"
anyhow = "1.0"
thiserror = "1.0"
dirs = "5.0"
chrono = "0.4"
libc = "0.2.180"
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "sync"] }
rand = "0.8"
qr2term = "0.3"
rust-embed = "8"
mime_guess = "2"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.26"
